//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSServerless_Google_Geocoding_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map
    {
        public int Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Name { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Address { get; set; }
        public string ExcelPath { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileCount { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public string CreateHost { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
